on:
    schedule:
        - cron:  "0 0 * * *"
    push:
        branches:
            - main
jobs:
    benchmark:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            distro:
              - humble
        steps:
            - uses: actions/checkout@v2
              with:
                path: src/rclpy_listeners
            - uses: ros-tooling/setup-ros@v0.6
              with:
                required-ros-distributions: ${{ matrix.distro }}
            - name: Install dependencies
              run: sudo apt-get install -y python3-pip
            - name: Install pip dependencies
              run: pip3 install -r src/rclpy_listeners/requirements.txt
            - name: Build 
              run: "source /opt/ros/${{ matrix.distro }}/setup.bash && colcon build"
            - name: Run benchmark
              run: "source /opt/ros/${{ matrix.distro }}/setup.bash && source install/local_setup.bash && ros2 run rclpy_listeners benchmark.py"
            - name: Upload results
              uses: actions/upload-artifact@v2
              with:
                  name: results
                  path: data.csv